### PR TITLE
Add ui script template

### PR DESCRIPTION
**Pull request by ry5n**
Adds a possible UI script template; uses the mobify/plugin factory, but imports it as a `Component` (a “Component factory”). The more I think about it, the more *something* like this makes sense to me:

- Component UI scripts should have some structure for consistency and to encourage good design;
- If they are going to provide some out-of-the-box structure, it may as well be the Plugin factory: we already use it for substantively similar things, and the implementation overhead is actually quite minimal.

Status: **Ready for review**

Reviewers: CS Eng team, @tedtate, @scalvert 
Ticket: [CSOPS-1270|https://mobify.atlassian.net/browse/CSOPS-1270]
Linked PRs: none

## Changes
- Still uses the mobify Plugin factory, but imports it as Component
- Adds some comments.

## How to test-drive this PR
- Code review only for now

## Research resources
- https://github.com/mobify/plugin
- http://addyosmani.com/resources/essentialjsdesignpatterns/book/#jquerypluginpatterns

### CODE REVIEW

**Comment by tedtate** [comment]
I don't think using `plugin` is the correct way to go here. Plugin is for creating jQuery plugins and I don't think these are jQuery plugins.

For me there are two requirements that this file needs to meet:

1) We enforce that a base set of methods are implemented by providing a default interface to extend from. This would provide things like `init`, `disable`, etc.
2) We allow for the composition of multiple stencils. In `plugin` this could be done through the use of `super` calls but I would prefer we do something like:

```
Component.init(childComponent, $element, options);
```

or for a more concrete example:

```
ProductList.init(responsiveGrid, $element, options);
```

Thoughts?

**Comment by ry5n** [comment]
> `ProductList.init(responsiveGrid, $element, options);`

So this would initialize a `responsiveGrid` that is being managed by `ProductList`?

**Comment by tedtate** [comment]
Yup. The assumption is that something like `ProductList` does some extra stuff over top of what `ResponsiveGrid` provides. I think in that example I should have used `ResponsiveGrid` as we want to pass in the component we want to instantiate not the already instantiated instance.

**Comment by tedtate** [comment]
Alternatively, if you only ever use `ResponsiveGrid` you can just call that directly from within the `ProductList` constructor and not pass it in as a parameter.

**Comment by ry5n** [comment]
I was expecting more the latter, where the parent instantiates children. The version where you pass the children in the constructor seems confusingly like inheritance, like ProductList is extending ResponsiveGrid.

I was hoping even that components could be more decoupled than this somehow. I don’t know how other modern frameworks are managing this.

**Comment by tedtate** [comment]
Yah, this is just another way of achieving the same behaviour that you get from inheritance. You would only need to do this if you had `ResponsiveGrid` and `StaticGrid` or something like that. Then as long as both of those components implement the same interface everything is hunky-dory.

http://en.wikipedia.org/wiki/Composition_over_inheritance

**Comment by ry5n** [comment]
After some offline discussion we decided this should be simplified until we get a handle on what the actual requirements are. Still not sure it’s right (we talked about an `init` method but not sure how that would fit in… I feel like there should be a constructor somewhere here… so that’s all this is right now).

**Comment by tedtate** [comment]
:+1:

**Pull request merged**
